name: Ubuntu
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Debug Session
      uses: wefew0213/urltestss@master
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        AC_DIRS: ${{ secrets.AC_DIRS }}
